[package]
name = "syscalls"
version = "0.5.0"
authors = ["Baojun Wang <wangbj@gmail.com>", "Jason White <rust@jasonwhite.io>"]
edition = "2018"
license = "BSD-2-Clause"
description = """
A list of Linux system calls.
"""
keywords = ["syscall", "linux"]
readme = "README.md"
repository = "https://github.com/jasonwhite/syscalls"
homepage = "https://github.com/jasonwhite/syscalls"
documentation = "https://docs.rs/syscalls"

[features]
default = ["std"]
std = []
with-serde = ["serde", "serde_repr"]

[dependencies]
lazy_static = "1"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_repr = { version = "0.1", optional = true }
paste = "1"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
libc = "0.2"

[workspace]
members = [
    "syscalls-gen",
]

[package.metadata.docs.rs]
features = ["std", "with-serde"]
